services:
  - type: web
    name: stripe-guardian-dev
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: development
      - key: PORT
        value: 8080
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: WIZNOTE_SUPABASE_URL
        sync: false
      - key: WIZNOTE_SUPABASE_SECRET_KEY
        sync: false
      - key: WIZNOTE_SUPABASE_SERVICE_KEY
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
